# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of Taproot.
#
# Taproot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Taproot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Taproot.  If not, see <https://www.gnu.org/licenses/>.

import os

WARNING_HEADER = '!!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!!'

FILE_TYPE_TO_COMMENT_FORMAT_MAP = {
    '.cpp': lambda warning: f'/*****************************************************************************/\n/********** {warning} **********/\n/*****************************************************************************/',
    '.hpp': lambda warning: f'/*****************************************************************************/\n/********** {warning} **********/\n/*****************************************************************************/',
    '.py': lambda warning: f'###############################################################################\n########### {warning} ###########\n###############################################################################',
    '.xml': lambda warning: f'<!-- {warning} -->',
}

def add_immutable_warning(path: str):
    '''
    Recurses through all files in `path` except for those specified in
    `DIRS_TO_IGNORE` below. For each file with an extension that is a
    key in `FILE_TYPE_TO_COMMENT_FORMAT_MAP`, adds the `FILE_TYPE_TO_COMMENT_FORMAT_MAP` string
    to the top of it (with the appropriate comment scheme for the given
    file type).

    @param path: script-relative path to code generated by taproot. When
    running this function from the `repo.lb` file in taproot, the path is
    just `./taproot`.
    '''
    DIRS_TO_IGNORE = [
        'modm',
        'sim-modm/hosted-darwin/modm',
        'sim-modm/hosted-linux/modm',
        'sim-modm/hosted-windows/modm',
    ]
    DIRS_TO_IGNORE = [os.path.normpath(os.path.join(path, p)) for p in DIRS_TO_IGNORE]

    for dirpath, dirnames, filenames in os.walk(path):
        dirnames[:] = [d for d in dirnames if os.path.normpath(os.path.join(dirpath, d)) not in DIRS_TO_IGNORE]

        for file in filenames:
            file = os.path.normpath(os.path.join(dirpath, file))

            file_ext = os.path.splitext(file)
            file_ext = file_ext[1] if len(file_ext) >= 2 else ''

            if file_ext in FILE_TYPE_TO_COMMENT_FORMAT_MAP:
                with open(file, 'r+') as f:
                    content = f.read()
                    f.seek(0, 0)
                    f.write(f'{FILE_TYPE_TO_COMMENT_FORMAT_MAP[file_ext](WARNING_HEADER)}\n\n{content}')
