# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of Taproot.
#
# Taproot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Taproot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Taproot.  If not, see <https://www.gnu.org/licenses/>.

import os

WARNING_HEADER = '!!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!!'

WARNING_COMMENT_TYPE = {
    '.cpp': lambda warning: f'// {warning}',
    '.hpp': lambda warning: f'// {warning}',
    '.py': lambda warning: f'# {warning}',
    '.xml': lambda warning: f'<!-- {warning} -->',
}

def add_immutable_warning(path: str):
    DIRS_TO_IGNORE = ['modm', 'sim-modm/hosted-darwin/modm', 'sim-modm/hosted-linux/modm', 'sim-modm/hosted-windows/modm']
    DIRS_TO_IGNORE = [os.path.normpath(os.path.join(path, p)) for p in DIRS_TO_IGNORE]

    for dirpath, dirnames, filenames in os.walk(path):
        dirnames[:] = [d for d in dirnames if os.path.normpath(os.path.join(dirpath, d)) not in DIRS_TO_IGNORE]

        for file in filenames:
            file = os.path.normpath(os.path.join(dirpath, file))

            file_ext = os.path.splitext(file)
            file_ext = file_ext[1] if len(file_ext) >= 2 else ''

            if file_ext in WARNING_COMMENT_TYPE:
                with open(file, 'r+') as f:
                    content = f.read()
                    f.seek(0, 0)
                    f.write(f'{WARNING_COMMENT_TYPE[file_ext](WARNING_HEADER)}\n\n{content}')
